services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Twig\AppContentExtension: ~

    App\Twig\ImageExtension: ~

    App\Twig\ContentPaginationExtension: ~

    App\Twig\AppLayoutExtension:
        arguments:
            $renderers: !tagged { tag: layout.renderer, index_by: key }

    App\Twig\AppLocationExtension: ~
