ezplatform:
    system:
        site_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"
            field_templates:
                - { template: '@ezdesign/fields/content_fields.html.twig', priority: 20 }
            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home

                    inspiration_list:
                        controller: "ez_query:pagingQueryAction"
                        template: "@ezdesign/full/inspiration_list.html.twig"
                        match:
                            Identifier\ContentType: [inspiration_list, inspiration_category]
                        params:
                            limit: 10
                            query:
                                query_type: "App:Children"
                                parameters:
                                    path_string: "@=location.pathString"
                                    depth: 5
                                    included_content_type_identifier: 'inspiration'
                                assign_results_to: inspirations
                    inspiration:
                        template: "@ezdesign/full/inspiration.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    store_list:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/store_list.html.twig"
                        match:
                            Identifier\ContentType: store_list
                        params:
                            query:
                                query_type: "App:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                    included_content_type_identifier: 'store'
                                assign_results_to: stores

                    store:
                        template: "@ezdesign/full/store.html.twig"
                        match:
                            Identifier\ContentType: store
                card:
                    inspiration:
                        template: "@ezdesign/card/inspiration.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    store:
                        template: "@ezdesign/card/store.html.twig"
                        match:
                            Identifier\ContentType: store
        professionals:
            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home

                    folder:
                        controller: "ez_query:pagingQueryAction"
                        template: "@ezdesign/full/folder.html.twig"
                        match:
                            Identifier\ContentType: folder
                        params:
                            limit: 12
                            query:
                                query_type: "App:Children"
                                parameters:
                                    path_string: "@=location.pathString"
                                    depth: 6
                                    included_content_type_identifier: 'professional'
                                assign_results_to: professionals

                    professional:
                        template: "@ezdesign/full/professional.html.twig"
                        match:
                            Identifier\ContentType: professional

                card:
                    professional:
                        template: "@ezdesign/card/professional.html.twig"
                        match:
                            Identifier\ContentType: professional

                    professional_catalog:
                        template: "@ezdesign/card/professional_catalog.html.twig"
                        match:
                            Identifier\ContentType: folder
