ezplatform:
    system:
        site_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"
            field_templates:
                - { template: '@ezdesign/fields/content_fields.html.twig', priority: 20 }
            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home

                    inspiration_list:
                        controller: "ez_query:pagingQueryAction"
                        template: "@ezdesign/full/inspiration_list.html.twig"
                        match:
                            Identifier\ContentType: [inspiration_list, inspiration_category]
                        params:
                            limit: 10
                            query:
                                query_type: "App:Children"
                                parameters:
                                    path_string: "@=location.pathString"
                                    depth: 5
                                    included_content_type_identifier: 'inspiration'
                                assign_results_to: inspirations
                    inspiration:
                        template: "@ezdesign/full/inspiration.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    store_list:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/store_list.html.twig"
                        match:
                            Identifier\ContentType: store_list
                        params:
                            query:
                                query_type: "App:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                    included_content_type_identifier: 'store'
                                assign_results_to: stores
                            professionals_location_id: '%app.professionals.location_id%'

                    store:
                        template: "@ezdesign/full/store.html.twig"
                        match:
                            Identifier\ContentType: store
                        params:
                            professionals_location_id: '%app.professionals.location_id%'

                    blog:
                        controller: "ez_query:pagingQueryAction"
                        template: "@ezdesign/full/blog.html.twig"
                        match:
                            Identifier\ContentType: blog
                        params:
                            query:
                                query_type: "App:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                    included_content_type_identifier: 'blog_post'
                                    sort_clauses: 'ascending'
                                assign_results_to: blog_post_list
                            subscribe_form_remote_id: "%app.subscribe_form.remote_id%"

                    blog_post:
                        template: "@ezdesign/full/blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post
                        params:
                            subscribe_form_remote_id: "%app.subscribe_form.remote_id%"

                    contact:
                        controller: App\Controller\ContactFormController:showContactFormAction
                        template: "@ezdesign/full/contact.html.twig"
                        match:
                            Identifier\ContentType: contact
                        params:
                            professionals_location_id: '%app.professionals.location_id%'

                card:
                    inspiration:
                        template: "@ezdesign/card/inspiration.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    store:
                        template: "@ezdesign/card/store.html.twig"
                        match:
                            Identifier\ContentType: store

                    blog_post:
                        template: "@ezdesign/card/blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post

                embed:
                    form:
                        template: "@ezdesign/embed/subscribe.html.twig"
                        match:
                            Identifier\ContentType: form
                            Id\Remote: "%app.subscribe_form.remote_id%"

                block_item:
                    inspiration:
                        template: "@ezdesign/block_item/inspiration/wide.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    default:
                        template: "@ezdesign/default/default.html.twig"
                        match:
                            Identifier\ContentType: [blog, blog_post, contact, article, store, store_list, inspiration_list, inspiration_category, home, landing_page, folder, file, video, image, gallery, form, user, user_group, professional]

        professionals:
            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home

                    folder:
                        controller: "ez_query:pagingQueryAction"
                        template: "@ezdesign/full/folder.html.twig"
                        match:
                            Identifier\ContentType: folder
                        params:
                            limit: 12
                            query:
                                query_type: "App:Children"
                                limit: 9
                                parameters:
                                    path_string: "@=location.pathString"
                                    depth: 6
                                    included_content_type_identifier: 'professional'
                                    main_location_only_for_depth_lower_than: 6
                                assign_results_to: professionals

                    professional:
                        template: "@ezdesign/full/professional.html.twig"
                        match:
                            Identifier\ContentType: professional

                card:
                    professional:
                        template: "@ezdesign/card/professional.html.twig"
                        match:
                            Identifier\ContentType: professional

                    professional_catalog:
                        template: "@ezdesign/card/professional_catalog.html.twig"
                        match:
                            Identifier\ContentType: folder
